// Code generated by go-swagger; DO NOT EDIT.

package name

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetScoreReader is a Reader for the GetScore structure.
type GetScoreReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScoreReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScoreOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetScoreOK creates a GetScoreOK with default headers values
func NewGetScoreOK() *GetScoreOK {
	return &GetScoreOK{}
}

/*
GetScoreOK describes a response with status code 200, with default header values.

OK
*/
type GetScoreOK struct {
	Payload int32
}

func (o *GetScoreOK) Error() string {
	return fmt.Sprintf("[GET /name/score][%d] getScoreOK  %+v", 200, o.Payload)
}
func (o *GetScoreOK) GetPayload() int32 {
	return o.Payload
}

func (o *GetScoreOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
